### ISSUE TITLE
Accept `map[string]T` instead of just `map[string]interface{}` in NamedQuery

### ISSUE THREAD

**Issue by tristanwietsma** [jmoiron/sqlx#114] opened 2014-12-30 19:20 UTC
When I execute

```go
// Test Handler
func TestQueryViewHandler(t *testing.T) {
        dsn := "postgres://postgres:@localhost:5432/test?sslmode=disable"
        db, err := sqlx.Open("postgres", dsn)
        if err != nil {
                t.Fatalf("open db failed %v", err)
        }
        err = db.Ping()
        if err != nil {
                t.Fatalf("ping failed %v", err)
        }

        params := map[string]string{
                "first": "Fat",
        }
        _, err = db.NamedQuery(`select * from people where first=:first`, params)
        if err != nil {
                t.Fatal(err.Error())
        }
}
```

I get the following error:

```bash
panic: reflect: call of github.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByName on map Value [recovered]
	panic: reflect: call of github.com/jmoiron/sqlx/reflectx.(*Mapper).TraversalsByName on map Value
```

Database connection is fine. Plain queries (no params) work fine. I'm working off the [docs](http://jmoiron.github.io/sqlx/) and there is a map example with NamedExec; I presume maps work with NamedQuery as well.

Any thoughts on that panic?

**Comment by jmoiron** [comment] 2015-04-17 15:51
This is actually a duplicate of #80 and I never realized.  I guess I wasn't so sure of myself on that one :)

**Closed** 2015-04-17 15:51 UTC
Labels: enhancement

**Comment by watercraft** [comment] 2018-06-28 17:33
Here is my attempt to follow this thread:
```golang
        // convert url params to acceptable arg for NamedExec()
        urlParams := map[string]interface{}{}
        for k, v := range mux.Vars(r) {
                urlParams[k] = v
        }

        db, err := sqlx.Connect("postgres", "host="+os.Getenv("PGHOST")+" user="+os.Getenv("PGUSER")+" password="+os.Getenv("PGPASSWORD")+" dbname="+os.Getenv("PGDATABASE")+" sslmode=disable")
        if err != nil {
                w.WriteHeader(400)
                w.Write([]byte(`{"error":"` + err.Error() + `"}`))
                return
        }
        _, err = db.NamedExec("delete from foo where id = ':id'", urlParams)
        if err != nil {
                w.WriteHeader(400)
                w.Write([]byte(`{"error":"` + err.Error() + `"}`))
                return
        }
```
Now I get:
```text
pq: invalid input syntax for type uuid: "$1"
```
Any ideas?

**Comment by watercraft** [comment] 2018-06-28 19:03
I'm working around this by putting the argument in a struct:
```golang
	// convert url param to acceptable arg for NamedExec()
	reqBody := types.Foo{Id: mux.Vars(r)["id"]}

	db, err := sqlx.Connect("postgres", "host="+os.Getenv("PGHOST")+" user="+os.Getenv("PGUSER")+" password="+os.Getenv("PGPASSWORD")+" dbname="+os.Getenv("PGDATABASE")+" sslmode=disable")
	if err != nil {
		w.WriteHeader(400)
		w.Write([]byte(`{"error":"` + err.Error() + `"}`))
		return
	}
	_, err = db.NamedExec("delete from foo where id = :id", &reqBody)
	if err != nil {
		w.WriteHeader(400)
		w.Write([]byte(`{"error":"` + err.Error() + `"}`))
		return
	}
```

**Comment by carmel** [comment] 2019-11-13 02:28
> I think I'm leaning towards wanting to accept maps of type `map[string]T` so I'm going to reopen this in anticipation of doing that.

Can consider this way：
![image](https://user-images.githubusercontent.com/36031579/68727786-5b50a580-0600-11ea-8629-baa877d947fa.png)
to>>>>>
![image](https://user-images.githubusercontent.com/36031579/68727794-61df1d00-0600-11ea-839b-35f13b7d7e8c.png)
